name = "lessonplan-api"
main = "worker.js"
compatibility_date = "2023-12-01"
node_compat = true

# 如果您的API需要访问KV存储、D1数据库或其他Cloudflare服务，请在此处配置

[vars]
# 在此处添加环境变量
NODE_ENV = "production"
PORT = "8787"

# 如需绑定自定义域名，请替换下方yourdomain.com为您的实际域名
[[routes]]
pattern = "api.yourdomain.com/*"
zone_name = "yourdomain.com"
