name = "lessonplan-backend"
main = "src/index.js"
compatibility_date = "2023-03-21"

[vars]
AI_API_URL = "https://dashscope.aliyuncs.com/compatible-mode/v1"
AI_MODEL_NAME = "qwq-plus"
NODE_ENV = "production"

# 添加自定义域名配置
# [[routes]]
# pattern = "api.lessonplan-app.com/*"
# zone_name = "lessonplan-app.com"
