name: 部署到Cloudflare Pages

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./client
        
    steps:
      - uses: actions/checkout@v3
      
      - name: 安装Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          
      - name: 安装依赖
        run: npm ci
        
      - name: 创建生产环境变量
        run: |
          echo "VITE_API_BASE_URL=https://api.lessonplan-app.com/api" > .env.production
      
      - name: 构建
        run: npm run build
          
      - name: 部署到Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: lessonplan-frontend
          directory: ./client/dist
          gitHubToken: ${{ secrets.GITHUB_TOKEN }} 